@startuml

skinparam backgroundColor transparent
skinparam RoundCorner 15
skinparam Padding 10
skinparam defaultTextAlignment center
skinparam ArrowColor black

left to right direction

rectangle "New\nQuarkus\nProject" as project
rectangle "Java 17" as java17
rectangle "Java 21" as java21 
rectangle "Java 24" as java24 #cccccc
rectangle "Maven" as maven #cccccc
rectangle "Gradle" as gradle 
rectangle "REST" as rest #cccccc
rectangle "Panache ORM" as jdbc #cccccc 

project --> java17
project --> java21
project --> java24

java24 --> maven
java24 --> gradle

maven --> rest
maven --> jdbc

@enduml