@startuml

skinparam backgroundColor transparent
skinparam RoundCorner 15
skinparam Padding 10
skinparam defaultTextAlignment center
skinparam ArrowColor black

left to right direction

rectangle "When is better \nto use Cursor AI" as project
rectangle "Greenfield project" as greenfield
rectangle "Project in production" as prodution 
rectangle "Prototype" as prototype 
rectangle "MVP" as mvp
rectangle "SLDC" as sldc
rectangle "Feature" as feature
rectangle "Refactoring" as refactoring 
rectangle "Testing" as testing 

project --> greenfield
project --> prodution
project --> prototype

greenfield --> mvp

prodution --> sldc
sldc --> feature
sldc --> refactoring
sldc --> testing

@enduml