openapi: 3.0.3
info:
  title: My JSON Server API
  description: API for retrieving data from My JSON Server
  version: 1.0.0
  contact:
    name: My JSON Server
    email: info@myjsonserver.example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://my-json-server.typicode.com/jabrena/latency-problems
paths:
  /greek:
    get:
      summary: Get Greek gods list
      description: Retrieve a list of Greek god names
      operationId: getGreekGods
      tags:
        - Greek Gods
      responses:
        '200':
          description: A list of Greek god names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["Zeus", "Hera", "Poseidon", "Demeter", "Athena", "Apollo"]
        '500':
          description: Internal server error